local addonName, NS = ...

-- =============================================================================
-- Species.lua  --  GENERATED, not hand-written. See the note at the bottom.
--
-- Every gathering node in the game: what it's called, what kind it is, which
-- expansion it belongs to, and every name it can wear.
--
-- WHY THIS IS A FLAT TABLE AND NOT SOMETHING CLEVER
--
-- The addon used to work all of this out at runtime, and got it wrong three
-- different ways at once:
--
--   * IDENTITY came from the item a node dropped. So a node had no name until
--     you'd picked one, mining was listed under "Copper Ore" rather than the
--     "Copper Vein" you actually see, and -- once seeded data arrived with its
--     own numbering -- two id spaces landed in one filter list and "Tranquility
--     Bloom" appeared TWICE, with two independent checkboxes.
--   * EXPANSION came from C_Item.GetItemInfo(id), which only ever worked because
--     that id happened to be an item. Once it wasn't, every herb got filed under
--     whatever expansion some unrelated item with the same number belonged to.
--   * NAMES came from whatever data pack happened to be installed.
--
-- The set of herbs in World of Warcraft is finite, known, and changes about once
-- a year. It does not need to be discovered at runtime, and discovering it is
-- what produced all three bugs. So it's written down.
--
-- VARIANTS ARE THE WHOLE POINT
--
-- The world doesn't call it "Azeroot". It calls it Lush Azeroot, Lightfused
-- Azeroot, Voidbound Azeroot, Wild Azeroot -- and the soft-target hands us that
-- name verbatim, which is why the filter list was filling up with near-duplicate
-- rows you'd have to tick five times to silence one plant.
--
-- They are ONE species. NS.SpeciesByName maps every name a node can wear -- base
-- or variant -- onto the single id that means it. One species, one row, one
-- checkbox.
-- =============================================================================


NS.Species = {
    HERB = {
        [401] = { name = "Peacebloom", expac = 0 },
        [402] = { name = "Silverleaf", expac = 0 },
        [403] = { name = "Earthroot", expac = 0 },
        [404] = { name = "Mageroyal", expac = 0 },
        [405] = { name = "Briarthorn", expac = 0 },
        [407] = { name = "Stranglekelp", expac = 0 },
        [408] = { name = "Bruiseweed", expac = 0 },
        [409] = { name = "Wild Steelbloom", expac = 0 },
        [410] = { name = "Grave Moss", expac = 0 },
        [411] = { name = "Kingsblood", expac = 0 },
        [412] = { name = "Liferoot", expac = 0 },
        [413] = { name = "Fadeleaf", expac = 0 },
        [414] = { name = "Goldthorn", expac = 0 },
        [415] = { name = "Khadgar's Whisker", expac = 0 },
        [416] = { name = "Wintersbite", expac = 0 },
        [417] = { name = "Firebloom", expac = 0 },
        [418] = { name = "Purple Lotus", expac = 0 },
        [420] = { name = "Arthas' Tears", expac = 0 },
        [421] = { name = "Sungrass", expac = 0 },
        [422] = { name = "Blindweed", expac = 0 },
        [423] = { name = "Ghost Mushroom", expac = 0 },
        [424] = { name = "Gromsblood", expac = 0 },
        [425] = { name = "Golden Sansam", expac = 0 },
        [426] = { name = "Dreamfoil", expac = 0 },
        [427] = { name = "Mountain Silversage", expac = 0 },
        [428] = { name = "Plaguebloom", expac = 0 },
        [429] = { name = "Icecap", expac = 0 },
        [431] = { name = "Black Lotus", expac = 0 },
        [432] = { name = "Felweed", expac = 1 },
        [433] = { name = "Dreaming Glory", expac = 1 },
        [434] = { name = "Terocone", expac = 1 },
        [435] = { name = "Ancient Lichen", expac = 1 },
        [436] = { name = "Bloodthistle", expac = 1 },
        [437] = { name = "Mana Thistle", expac = 1 },
        [438] = { name = "Netherbloom", expac = 1 },
        [439] = { name = "Nightmare Vine", expac = 1 },
        [440] = { name = "Ragveil", expac = 1 },
        [441] = { name = "Flame Cap", expac = 1 },
        [442] = { name = "Netherdust Bush", expac = 1 },
        [443] = { name = "Adder's Tongue", expac = 2 },
        [446] = { name = "Goldclover", expac = 2 },
        [447] = { name = "Icethorn", expac = 2 },
        [448] = { name = "Lichbloom", expac = 2 },
        [449] = { name = "Talandra's Rose", expac = 2 },
        [450] = { name = "Tiger Lily", expac = 2 },
        [451] = { name = "Firethorn", expac = 2 },
        [452] = { name = "Frozen Herb", expac = 2 },
        [453] = { name = "Frost Lotus", expac = 2 },
        [454] = { name = "Dragon's Teeth", expac = 3 },
        [455] = { name = "Sorrowmoss", expac = 3 },
        [456] = { name = "Azshara's Veil", expac = 3 },
        [457] = { name = "Cinderbloom", expac = 3 },
        [458] = { name = "Stormvine", expac = 3 },
        [459] = { name = "Heartblossom", expac = 3 },
        [460] = { name = "Twilight Jasmine", expac = 3 },
        [461] = { name = "Whiptail", expac = 3 },
        [462] = { name = "Golden Lotus", expac = 4 },
        [463] = { name = "Fool's Cap", expac = 4 },
        [464] = { name = "Snow Lily", expac = 4 },
        [465] = { name = "Silkweed", expac = 4 },
        [466] = { name = "Green Tea Leaf", expac = 4 },
        [467] = { name = "Rain Poppy", expac = 4 },
        [468] = { name = "Sha-Touched Herb", expac = 4 },
        [469] = { name = "Talador Orchid", expac = 5 },
        [470] = { name = "Nagrand Arrowbloom", expac = 5 },
        [471] = { name = "Starflower", expac = 5 },
        [472] = { name = "Gorgrond Flytrap", expac = 5 },
        [473] = { name = "Fireweed", expac = 5 },
        [474] = { name = "Frostweed", expac = 5 },
        [475] = { name = "Withered Herb", expac = 5 },
        [476] = { name = "Aethril", expac = 6 },
        [477] = { name = "Dreamleaf", expac = 6 },
        [478] = { name = "Felwort", expac = 6 },
        [479] = { name = "Fjarnskaggl", expac = 6 },
        [480] = { name = "Foxflower", expac = 6 },
        [481] = { name = "Starlight Rose", expac = 6 },
        [482] = { name = "Fel-Encrusted Herb", expac = 6 },
        [483] = { name = "Fel-Encrusted Herb Cluster", expac = 6 },
        [484] = { name = "Astral Glory", expac = 6 },
        [485] = { name = "Akunda's Bite", expac = 7 },
        [486] = { name = "Anchor Weed", expac = 7 },
        [487] = { name = "Riverbud", expac = 7 },
        [488] = { name = "Sea Stalks", expac = 7 },
        [489] = { name = "Siren's Sting", expac = 7 },
        [490] = { name = "Star Moss", expac = 7 },
        [491] = { name = "Winter's Kiss", expac = 7 },
        [492] = { name = "Zin'anthid", expac = 7 },
        [493] = { name = "Death Blossom", expac = 8 },
        [494] = { name = "Nightshade", expac = 8 },
        [495] = { name = "Marrowroot", expac = 8 },
        [496] = { name = "Vigil's Torch", expac = 8 },
        [497] = { name = "Rising Glory", expac = 8 },
        [498] = { name = "Widowbloom", expac = 8 },
        [499] = { name = "First Flower", expac = 8 },
        [1407] = { name = "Hochenblume", expac = 9 },
        [1414] = { name = "Bubble Poppy", expac = 9 },
        [1421] = { name = "Saxifrage", expac = 9 },
        [1428] = { name = "Writhebark", expac = 9 },
        [1439] = { name = "Mycobloom", expac = 10 },
        [1447] = { name = "Blessing Blossom", expac = 10 },
        [1455] = { name = "Luredrop", expac = 10 },
        [1463] = { name = "Orbinid", expac = 10 },
        [1471] = { name = "Arathor's Spear", expac = 10 },
        [1479] = { name = "Phantom Bloom", expac = 10 },
        [1481] = { name = "Argentleaf", expac = 11 },
        [1482] = { name = "Azeroot", expac = 11 },
        [1483] = { name = "Mana Lily", expac = 11 },
        [1484] = { name = "Sanguithorn", expac = 11 },
        [1485] = { name = "Tranquility Bloom", expac = 11 },
    },
    MINE = {
        [201] = { name = "Copper Vein", expac = 0 },
        [202] = { name = "Tin Vein", expac = 0 },
        [203] = { name = "Iron Deposit", expac = 0 },
        [204] = { name = "Silver Vein", expac = 0 },
        [205] = { name = "Gold Vein", expac = 0 },
        [206] = { name = "Mithril Deposit", expac = 0 },
        [207] = { name = "Ooze Covered Mithril Deposit", expac = 0 },
        [208] = { name = "Truesilver Deposit", expac = 0 },
        [209] = { name = "Ooze Covered Silver Vein", expac = 0 },
        [210] = { name = "Ooze Covered Gold Vein", expac = 0 },
        [211] = { name = "Ooze Covered Truesilver Deposit", expac = 0 },
        [212] = { name = "Ooze Covered Rich Thorium Vein", expac = 0 },
        [213] = { name = "Ooze Covered Thorium Vein", expac = 0 },
        [214] = { name = "Small Thorium Vein", expac = 0 },
        [215] = { name = "Rich Thorium Vein", expac = 0 },
        [217] = { name = "Dark Iron Deposit", expac = 0 },
        [218] = { name = "Lesser Bloodstone Deposit", expac = 0 },
        [219] = { name = "Incendicite Mineral Vein", expac = 0 },
        [220] = { name = "Indurium Mineral Vein", expac = 0 },
        [221] = { name = "Fel Iron Deposit", expac = 1 },
        [222] = { name = "Adamantite Deposit", expac = 1 },
        [223] = { name = "Rich Adamantite Deposit", expac = 1 },
        [224] = { name = "Khorium Vein", expac = 1 },
        [225] = { name = "Large Obsidian Chunk", expac = 1 },
        [226] = { name = "Small Obsidian Chunk", expac = 1 },
        [227] = { name = "Nethercite Deposit", expac = 1 },
        [228] = { name = "Cobalt Deposit", expac = 2 },
        [229] = { name = "Rich Cobalt Deposit", expac = 2 },
        [230] = { name = "Titanium Vein", expac = 2 },
        [231] = { name = "Saronite Deposit", expac = 2 },
        [232] = { name = "Rich Saronite Deposit", expac = 2 },
        [233] = { name = "Obsidium Deposit", expac = 3 },
        [235] = { name = "Pure Saronite Deposit", expac = 3 },
        [236] = { name = "Elementium Vein", expac = 3 },
        [237] = { name = "Rich Elementium Vein", expac = 3 },
        [238] = { name = "Pyrite Deposit", expac = 3 },
        [239] = { name = "Rich Obsidium Deposit", expac = 3 },
        [240] = { name = "Rich Pyrite Deposit", expac = 3 },
        [241] = { name = "Ghost Iron Deposit", expac = 4 },
        [242] = { name = "Rich Ghost Iron Deposit", expac = 4 },
        [245] = { name = "Kyparite Deposit", expac = 4 },
        [246] = { name = "Rich Kyparite Deposit", expac = 4 },
        [247] = { name = "Trillium Vein", expac = 4 },
        [248] = { name = "Rich Trillium Vein", expac = 4 },
        [249] = { name = "True Iron Deposit", expac = 5 },
        [250] = { name = "Rich True Iron Deposit", expac = 5 },
        [251] = { name = "Blackrock Deposit", expac = 5 },
        [252] = { name = "Rich Blackrock Deposit", expac = 5 },
        [253] = { name = "Leystone Deposit", expac = 6 },
        [254] = { name = "Rich Leystone Deposit", expac = 6 },
        [255] = { name = "Leystone Seam", expac = 6 },
        [256] = { name = "Felslate Deposit", expac = 6 },
        [257] = { name = "Rich Felslate Deposit", expac = 6 },
        [258] = { name = "Felslate Seam", expac = 6 },
        [259] = { name = "Empyrium Deposit", expac = 6 },
        [260] = { name = "Rich Empyrium Deposit", expac = 6 },
        [261] = { name = "Empyrium Seam", expac = 6 },
        [262] = { name = "Monelite Deposit", expac = 7 },
        [263] = { name = "Rich Monelite Deposit", expac = 7 },
        [264] = { name = "Monelite Seam", expac = 7 },
        [265] = { name = "Platinum Deposit", expac = 7 },
        [266] = { name = "Rich Platinum Deposit", expac = 7 },
        [267] = { name = "Storm Silver Deposit", expac = 7 },
        [268] = { name = "Rich Storm Silver Deposit", expac = 7 },
        [269] = { name = "Storm Silver Seam", expac = 7 },
        [270] = { name = "Osmenite Deposit", expac = 7 },
        [271] = { name = "Rich Osmenite Deposit", expac = 7 },
        [272] = { name = "Osmenite Seam", expac = 7 },
        [273] = { name = "Laestrite Deposit", expac = 8 },
        [274] = { name = "Rich Laestrite Deposit", expac = 8 },
        [275] = { name = "Phaedrum Deposit", expac = 8 },
        [276] = { name = "Rich Phaedrum Deposit", expac = 8 },
        [277] = { name = "Oxxein Deposit", expac = 8 },
        [278] = { name = "Rich Oxxein Deposit", expac = 8 },
        [280] = { name = "Elethium Deposit", expac = 8 },
        [282] = { name = "Solenium Deposit", expac = 8 },
        [283] = { name = "Rich Solenium Deposit", expac = 8 },
        [284] = { name = "Sinvyr Deposit", expac = 8 },
        [285] = { name = "Rich Sinvyr Deposit", expac = 8 },
        [287] = { name = "Progenium Deposit", expac = 8 },
        [1200] = { name = "Serevite Seam", expac = 9 },
        [1201] = { name = "Serevite Deposit", expac = 9 },
        [1208] = { name = "Draconium Seam", expac = 9 },
        [1218] = { name = "Bismuth", expac = 10 },
        [1225] = { name = "Bismuth Seam", expac = 10 },
        [1226] = { name = "Aqirite", expac = 10 },
        [1233] = { name = "Aqirite Seam", expac = 10 },
        [1234] = { name = "Ironclaw", expac = 10 },
        [1241] = { name = "Ironclaw Seam", expac = 10 },
        [1242] = { name = "Webbed Ore Deposit", expac = 10 },
        [1243] = { name = "Desolate Deposit", expac = 10 },
        [1245] = { name = "Brilliant Silver", expac = 11 },
        [1246] = { name = "Brilliant Silver Seam", expac = 11 },
        [1247] = { name = "Refulgent Copper", expac = 11 },
        [1248] = { name = "Refulgent Copper Seam", expac = 11 },
        [1249] = { name = "Umbral Tin", expac = 11 },
        [1250] = { name = "Umbral Tin Seam", expac = 11 },
    },
    LUMBER = {
        [701] = { name = "Small Timber", expac = 0 },
        [702] = { name = "Timber", expac = 0 },
        [703] = { name = "Large Timber", expac = 0 },
        [704] = { name = "Ironwood Lumber", expac = 10 },
        [705] = { name = "Olemba Lumber", expac = 10 },
        [706] = { name = "Coldwind Lumber", expac = 10 },
        [707] = { name = "Ashwood Lumber", expac = 10 },
        [708] = { name = "Bamboo Lumber", expac = 10 },
        [709] = { name = "Shadowmoon Lumber", expac = 10 },
        [710] = { name = "Fel-Touched Lumber", expac = 10 },
        [711] = { name = "Darkpine Lumber", expac = 10 },
        [712] = { name = "Arden Lumber", expac = 10 },
        [713] = { name = "Dragonpine Lumber", expac = 10 },
        [714] = { name = "Dornic Fir Lumber", expac = 10 },
        [715] = { name = "Thalassian Lumber", expac = 11 },
    },
    FISHING = {
        [101] = { name = "Floating Wreckage", expac = 0 },
        [103] = { name = "Floating Debris", expac = 0 },
        [105] = { name = "Firefin Snapper School", expac = 0 },
        [106] = { name = "Greater Sagefish School", expac = 0 },
        [107] = { name = "Oily Blackmouth School", expac = 0 },
        [108] = { name = "Sagefish School", expac = 0 },
        [109] = { name = "School of Deviate Fish", expac = 0 },
        [110] = { name = "Stonescale Eel Swarm", expac = 0 },
        [112] = { name = "Highland Mixed School", expac = 1 },
        [113] = { name = "Pure Water", expac = 1 },
        [114] = { name = "Bluefish School", expac = 1 },
        [115] = { name = "Feltail School", expac = 1 },
        [115] = { name = "Brackish Mixed School", expac = 1 },
        [116] = { name = "Mudfish School", expac = 1 },
        [117] = { name = "School of Darter", expac = 1 },
        [118] = { name = "Sporefish School", expac = 1 },
        [119] = { name = "Steam Pump Flotsam", expac = 1 },
        [120] = { name = "School of Tastyfish", expac = 1 },
        [121] = { name = "Borean Man O' War School", expac = 2 },
        [122] = { name = "Deep Sea Monsterbelly School", expac = 2 },
        [123] = { name = "Dragonfin Angelfish School", expac = 2 },
        [124] = { name = "Fangtooth Herring School", expac = 2 },
        [125] = { name = "Floating Wreckage Pool", expac = 2 },
        [126] = { name = "Glacial Salmon School", expac = 2 },
        [127] = { name = "Glassfin Minnow School", expac = 2 },
        [128] = { name = "Imperial Manta Ray School", expac = 2 },
        [129] = { name = "Moonglow Cuttlefish School", expac = 2 },
        [130] = { name = "Musselback Sculpin School", expac = 2 },
        [131] = { name = "Nettlefish School", expac = 2 },
        [132] = { name = "Strange Pool", expac = 2 },
        [133] = { name = "Schooner Wreckage", expac = 2 },
        [134] = { name = "Waterlogged Wreckage Pool", expac = 2 },
        [135] = { name = "Bloodsail Wreckage Pool", expac = 2 },
        [136] = { name = "Mixed Ocean School", expac = 2 },
        [149] = { name = "Albino Cavefish School", expac = 2 },
        [151] = { name = "Blackbelly Mudfish School", expac = 2 },
        [152] = { name = "Fathom Eel Swarm", expac = 2 },
        [153] = { name = "Highland Guppy School", expac = 2 },
        [154] = { name = "Mountain Trout School", expac = 2 },
        [155] = { name = "Pool of Fire", expac = 2 },
        [156] = { name = "Shipwreck Debris", expac = 2 },
        [157] = { name = "Deepsea Sagefish School", expac = 2 },
        [158] = { name = "Emperor Salmon School", expac = 4 },
        [159] = { name = "Giant Mantis Shrimp Swarm", expac = 4 },
        [160] = { name = "Golden Carp School", expac = 4 },
        [161] = { name = "Jade Lungfish School", expac = 4 },
        [162] = { name = "Krasarang Paddlefish School", expac = 4 },
        [163] = { name = "Redbelly Mandarin School", expac = 4 },
        [164] = { name = "Reef Octopus Swarm", expac = 4 },
        [165] = { name = "Floating Shipwreck Debris", expac = 4 },
        [166] = { name = "Jewel Danio School", expac = 4 },
        [167] = { name = "Spinefish School", expac = 4 },
        [168] = { name = "Tiger Gourami School", expac = 4 },
        [169] = { name = "Abyssal Gulper School", expac = 5 },
        [170] = { name = "Oily Abyssal Gulper School", expac = 5 },
        [171] = { name = "Blackwater Whiptail School", expac = 5 },
        [172] = { name = "Blind Lake Sturgeon School", expac = 5 },
        [173] = { name = "Fat Sleeper School", expac = 5 },
        [174] = { name = "Fire Ammonite School", expac = 5 },
        [175] = { name = "Jawless Skulker School", expac = 5 },
        [176] = { name = "Sea Scorpion School", expac = 5 },
        [177] = { name = "Oily Sea Scorpion School", expac = 5 },
        [178] = { name = "Savage Piranha Pool", expac = 5 },
        [181] = { name = "Felmouth Frenzy School", expac = 5 },
        [182] = { name = "Black Barracuda School", expac = 6 },
        [183] = { name = "Cursed Queenfish School", expac = 6 },
        [184] = { name = "Runescale Koi School", expac = 6 },
        [185] = { name = "Fever of Stormrays", expac = 6 },
        [186] = { name = "Highmountain Salmon School", expac = 6 },
        [187] = { name = "Mossgill Perch School", expac = 6 },
        [188] = { name = "Frenzied Fangtooth School", expac = 7 },
        [189] = { name = "Great Sea Catfish School", expac = 7 },
        [190] = { name = "Lane Snapper School", expac = 7 },
        [191] = { name = "Rasboralus School", expac = 7 },
        [192] = { name = "Redtail Loach School", expac = 7 },
        [193] = { name = "Sand Shifter School", expac = 7 },
        [194] = { name = "Slimy Mackerel School", expac = 7 },
        [195] = { name = "Tiragarde Perch School", expac = 7 },
        [196] = { name = "U'taka School", expac = 7 },
        [197] = { name = "Mauve Stinger School", expac = 7 },
        [198] = { name = "Viper Fish School", expac = 7 },
        [199] = { name = "Ionized Minnows", expac = 7 },
        [1101] = { name = "Sentry Fish School", expac = 7 },
        [1102] = { name = "Iridescent Amberjack School", expac = 8 },
        [1103] = { name = "Pocked Bonefish School", expac = 8 },
        [1104] = { name = "Silvergill Pike School", expac = 8 },
        [1105] = { name = "Elysian Thade School", expac = 8 },
        [1106] = { name = "Lost Sole School", expac = 8 },
        [1107] = { name = "Spinefin Piranha School", expac = 8 },
        [1108] = { name = "Precursor Placoderm School", expac = 8 },
        [1109] = { name = "Islefin Dorado Pool", expac = 9 },
        [1110] = { name = "Shimmering Treasure Pool", expac = 9 },
        [1111] = { name = "Temporal Dragonhead Pool", expac = 9 },
        [1112] = { name = "Thousandbite Pirahna Swarm", expac = 9 },
        [1113] = { name = "Aileron Seamoth School", expac = 9 },
        [1114] = { name = "Cerulean Spinefish School", expac = 9 },
        [1115] = { name = "Rimefin Tuna Pool", expac = 9 },
        [1116] = { name = "Magma Thresher Pool", expac = 9 },
        [1117] = { name = "Prismatic Leaper School", expac = 9 },
        [1118] = { name = "Calm Surfacing Ripple", expac = 10 },
        [1119] = { name = "River Bass Pool", expac = 10 },
        [1120] = { name = "Glimmerpool", expac = 10 },
        [1121] = { name = "Bloody Perch Swarm", expac = 10 },
        [1122] = { name = "Swarm of Slum Sharks", expac = 10 },
        [1123] = { name = "Blood in the Water", expac = 10 },
        [1124] = { name = "Festering Rotpool", expac = 10 },
        [1125] = { name = "Infused Ichor Spill", expac = 10 },
        [1126] = { name = "Stargazer Swarm", expac = 10 },
        [1127] = { name = "Anglerseeker Torrent", expac = 10 },
        [1128] = { name = "Royal Ripple", expac = 10 },
        [1129] = { name = "Shore Treasure", expac = 10 },
        [1130] = { name = "Floating Deep Treasure", expac = 10 },
        [1131] = { name = "Bloom Swarm", expac = 11 },
        [1132] = { name = "Blossoming Torrent", expac = 11 },
        [1133] = { name = "Bubbling Bloom", expac = 11 },
        [1134] = { name = "Hunter Surge", expac = 11 },
        [1135] = { name = "Lashing Waves", expac = 11 },
        [1136] = { name = "Obscured School", expac = 11 },
        [1137] = { name = "Salmon Pool", expac = 11 },
        [1138] = { name = "Song Swarm", expac = 11 },
        [1139] = { name = "Sunbath School", expac = 11 },
        [1140] = { name = "Sunwell Swarm", expac = 11 },
        [1141] = { name = "Surface Ripple", expac = 11 },
        [1142] = { name = "Careless Cargo", expac = 11 },
        [1143] = { name = "Lost Treasures", expac = 11 },
        [1144] = { name = "Viscous Void", expac = 11 },
    },
    TREASURE = {
        [501] = { name = "Giant Clam", expac = 0 },
        [502] = { name = "Battered Chest", expac = 0 },
        [503] = { name = "Tattered Chest", expac = 0 },
        [504] = { name = "Solid Chest", expac = 0 },
        [505] = { name = "Large Iron Bound Chest", expac = 0 },
        [506] = { name = "Large Solid Chest", expac = 0 },
        [507] = { name = "Large Battered Chest", expac = 0 },
        [508] = { name = "Buccaneer's Strongbox", expac = 0 },
        [509] = { name = "Large Mithril Bound Chest", expac = 0 },
        [510] = { name = "Large Darkwood Chest", expac = 0 },
        [512] = { name = "Bloodpetal Sprout", expac = 0 },
        [514] = { name = "Practice Lockbox", expac = 0 },
        [515] = { name = "Battered Footlocker", expac = 0 },
        [516] = { name = "Waterlogged Footlocker", expac = 0 },
        [517] = { name = "Dented Footlocker", expac = 0 },
        [518] = { name = "Mossy Footlocker", expac = 0 },
        [519] = { name = "Scarlet Footlocker", expac = 0 },
        [520] = { name = "Burial Chest", expac = 0 },
        [521] = { name = "Fel Iron Chest", expac = 0 },
        [522] = { name = "Heavy Fel Iron Chest", expac = 0 },
        [523] = { name = "Adamantite Bound Chest", expac = 0 },
        [524] = { name = "Felsteel Chest", expac = 0 },
        [525] = { name = "Glowcap", expac = 0 },
        [526] = { name = "Wicker Chest", expac = 0 },
        [527] = { name = "Primitive Chest", expac = 0 },
        [528] = { name = "Solid Fel Iron Chest", expac = 0 },
        [529] = { name = "Bound Fel Iron Chest", expac = 0 },
        [530] = { name = "Bound Adamantite Chest", expac = 0 },
        [531] = { name = "Netherwing Egg", expac = 0 },
        [532] = { name = "Everfrost Chip", expac = 0 },
        [533] = { name = "Brightly Colored Egg", expac = 0 },
        [534] = { name = "Silken Treasure Chest", expac = 0 },
        [535] = { name = "Sturdy Treasure Chest", expac = 0 },
        [536] = { name = "Runestone Treasure Chest", expac = 0 },
        [537] = { name = "Silverbound Treasure Chest", expac = 0 },
        [538] = { name = "Mysterious Camel Figurine", expac = 0 },
        [539] = { name = "Dark Iron Treasure Chest", expac = 0 },
        [540] = { name = "Maplewood Treasure Chest", expac = 0 },
        [541] = { name = "Takk's Nest", expac = 0 },
        [542] = { name = "Dart's Nest", expac = 0 },
        [543] = { name = "Razormaw Matriarch's Nest", expac = 0 },
        [544] = { name = "Ravasaur Matriarch's Nest", expac = 0 },
        [545] = { name = "Dark Soil", expac = 0 },
        [546] = { name = "Onyx Egg", expac = 0 },
        [547] = { name = "Trove of the Thunder King", expac = 0 },
        [548] = { name = "Highmaul Reliquary", expac = 0 },
        [549] = { name = "Suspiciously Glowing Chest", expac = 0 },
        [550] = { name = "Radiating Apexis Shard", expac = 0 },
        [551] = { name = "Gleaming Draenic Chest", expac = 0 },
        [552] = { name = "Ancient Mana Shard", expac = 6 },
        [553] = { name = "Ancient Mana Chunk", expac = 6 },
        [554] = { name = "Ancient Mana Crystal", expac = 6 },
        [555] = { name = "Leypetal Blossom", expac = 6 },
        [556] = { name = "Leypetal Powder", expac = 6 },
        [557] = { name = "Glowing Tome", expac = 6 },
        [558] = { name = "Mana-Infused Gem", expac = 6 },
        [559] = { name = "Twice-Fortified Arcwine", expac = 6 },
        [560] = { name = "Mechanized Chest", expac = 7 },
        [561] = { name = "Glimmering Chest", expac = 7 },
        [562] = { name = "Prismatic Crystal", expac = 7 },
        [563] = { name = "Jelly Deposit", expac = 7 },
        [564] = { name = "Large Jelly Deposit", expac = 7 },
        [565] = { name = "Ground Wart", expac = 8 },
        [566] = { name = "Disturbed Earth", expac = 10 },
    },
}

-- Every name the world might use -> the one species it means.
-- This is what Live.lua classifies a soft-target against, which is why the addon
-- no longer needs GatherMate installed to know a herb from a stool.
NS.SpeciesByName = {
    ["Adder's Tongue"] = { type = "HERB", id = 443 },
    ["Aethril"] = { type = "HERB", id = 476 },
    ["Akunda's Bite"] = { type = "HERB", id = 485 },
    ["Anchor Weed"] = { type = "HERB", id = 486 },
    ["Ancient Lichen"] = { type = "HERB", id = 435 },
    ["Arathor's Spear"] = { type = "HERB", id = 1471 },
    ["Lush Arathor's Spear"] = { type = "HERB", id = 1471 },
    ["Irradiated Arathor's Spear"] = { type = "HERB", id = 1471 },
    ["Sporefused Arathor's Spear"] = { type = "HERB", id = 1471 },
    ["Sporelusive Arathor's Spear"] = { type = "HERB", id = 1471 },
    ["Crystallized Arathor's Spear"] = { type = "HERB", id = 1471 },
    ["Altered Arathor's Spear"] = { type = "HERB", id = 1471 },
    ["Camouflaged Arathor's Spear"] = { type = "HERB", id = 1471 },
    ["Argentleaf"] = { type = "HERB", id = 1481 },
    ["Lush Argentleaf"] = { type = "HERB", id = 1481 },
    ["Lightfused Argentleaf"] = { type = "HERB", id = 1481 },
    ["Primal Argentleaf"] = { type = "HERB", id = 1481 },
    ["Transplanted Argentleaf"] = { type = "HERB", id = 1481 },
    ["Transplanted Lush Argentleaf"] = { type = "HERB", id = 1481 },
    ["Voidbound Argentleaf"] = { type = "HERB", id = 1481 },
    ["Wild Argentleaf"] = { type = "HERB", id = 1481 },
    ["Arthas' Tears"] = { type = "HERB", id = 420 },
    ["Astral Glory"] = { type = "HERB", id = 484 },
    ["Azeroot"] = { type = "HERB", id = 1482 },
    ["Lush Azeroot"] = { type = "HERB", id = 1482 },
    ["Lightfused Azeroot"] = { type = "HERB", id = 1482 },
    ["Primal Azeroot"] = { type = "HERB", id = 1482 },
    ["Transplanted Azeroot"] = { type = "HERB", id = 1482 },
    ["Transplanted Lush Azeroot"] = { type = "HERB", id = 1482 },
    ["Voidbound Azeroot"] = { type = "HERB", id = 1482 },
    ["Wild Azeroot"] = { type = "HERB", id = 1482 },
    ["Azshara's Veil"] = { type = "HERB", id = 456 },
    ["Black Lotus"] = { type = "HERB", id = 431 },
    ["Blessing Blossom"] = { type = "HERB", id = 1447 },
    ["Lush Blessing Blossom"] = { type = "HERB", id = 1447 },
    ["Irradiated Blessing Blossom"] = { type = "HERB", id = 1447 },
    ["Sporefused Blessing Blossom"] = { type = "HERB", id = 1447 },
    ["Sporelusive Blessing Blossom"] = { type = "HERB", id = 1447 },
    ["Crystallized Blessing Blossom"] = { type = "HERB", id = 1447 },
    ["Altered Blessing Blossom"] = { type = "HERB", id = 1447 },
    ["Camouflaged Blessing Blossom"] = { type = "HERB", id = 1447 },
    ["Blindweed"] = { type = "HERB", id = 422 },
    ["Bloodthistle"] = { type = "HERB", id = 436 },
    ["Briarthorn"] = { type = "HERB", id = 405 },
    ["Bruiseweed"] = { type = "HERB", id = 408 },
    ["Bubble Poppy"] = { type = "HERB", id = 1414 },
    ["Lush Bubble Poppy"] = { type = "HERB", id = 1414 },
    ["Frigid Bubble Poppy"] = { type = "HERB", id = 1414 },
    ["Decayed Bubble Poppy"] = { type = "HERB", id = 1414 },
    ["Windswept Bubble Poppy"] = { type = "HERB", id = 1414 },
    ["Infurious Bubble Poppy"] = { type = "HERB", id = 1414 },
    ["Titan-Touched Bubble Poppy"] = { type = "HERB", id = 1414 },
    ["Lambent Bubble Poppy"] = { type = "HERB", id = 1414 },
    ["Cinderbloom"] = { type = "HERB", id = 457 },
    ["Death Blossom"] = { type = "HERB", id = 493 },
    ["Dragon's Teeth"] = { type = "HERB", id = 454 },
    ["Dreamfoil"] = { type = "HERB", id = 426 },
    ["Dreaming Glory"] = { type = "HERB", id = 433 },
    ["Dreamleaf"] = { type = "HERB", id = 477 },
    ["Earthroot"] = { type = "HERB", id = 403 },
    ["Fadeleaf"] = { type = "HERB", id = 413 },
    ["Fel-Encrusted Herb"] = { type = "HERB", id = 482 },
    ["Fel-Encrusted Herb Cluster"] = { type = "HERB", id = 483 },
    ["Felweed"] = { type = "HERB", id = 432 },
    ["Felwort"] = { type = "HERB", id = 478 },
    ["Firebloom"] = { type = "HERB", id = 417 },
    ["Firethorn"] = { type = "HERB", id = 451 },
    ["Fireweed"] = { type = "HERB", id = 473 },
    ["First Flower"] = { type = "HERB", id = 499 },
    ["Lush First Flower"] = { type = "HERB", id = 499 },
    ["Elusive First Flower"] = { type = "HERB", id = 499 },
    ["Lush Elusive First Flower"] = { type = "HERB", id = 499 },
    ["Fjarnskaggl"] = { type = "HERB", id = 479 },
    ["Flame Cap"] = { type = "HERB", id = 441 },
    ["Fool's Cap"] = { type = "HERB", id = 463 },
    ["Foxflower"] = { type = "HERB", id = 480 },
    ["Frost Lotus"] = { type = "HERB", id = 453 },
    ["Frostweed"] = { type = "HERB", id = 474 },
    ["Frozen Herb"] = { type = "HERB", id = 452 },
    ["Ghost Mushroom"] = { type = "HERB", id = 423 },
    ["Goldclover"] = { type = "HERB", id = 446 },
    ["Golden Lotus"] = { type = "HERB", id = 462 },
    ["Golden Sansam"] = { type = "HERB", id = 425 },
    ["Goldthorn"] = { type = "HERB", id = 414 },
    ["Gorgrond Flytrap"] = { type = "HERB", id = 472 },
    ["Grave Moss"] = { type = "HERB", id = 410 },
    ["Green Tea Leaf"] = { type = "HERB", id = 466 },
    ["Gromsblood"] = { type = "HERB", id = 424 },
    ["Heartblossom"] = { type = "HERB", id = 459 },
    ["Hochenblume"] = { type = "HERB", id = 1407 },
    ["Lush Hochenblume"] = { type = "HERB", id = 1407 },
    ["Frigid Hochenblume"] = { type = "HERB", id = 1407 },
    ["Decayed Hochenblume"] = { type = "HERB", id = 1407 },
    ["Windswept Hochenblume"] = { type = "HERB", id = 1407 },
    ["Infurious Hochenblume"] = { type = "HERB", id = 1407 },
    ["Titan-Touched Hochenblume"] = { type = "HERB", id = 1407 },
    ["Lambent Hochenblume"] = { type = "HERB", id = 1407 },
    ["Icecap"] = { type = "HERB", id = 429 },
    ["Icethorn"] = { type = "HERB", id = 447 },
    ["Khadgar's Whisker"] = { type = "HERB", id = 415 },
    ["Kingsblood"] = { type = "HERB", id = 411 },
    ["Lichbloom"] = { type = "HERB", id = 448 },
    ["Liferoot"] = { type = "HERB", id = 412 },
    ["Luredrop"] = { type = "HERB", id = 1455 },
    ["Lush Luredrop"] = { type = "HERB", id = 1455 },
    ["Irradiated Luredrop"] = { type = "HERB", id = 1455 },
    ["Sporefused Luredrop"] = { type = "HERB", id = 1455 },
    ["Sporelusive Luredrop"] = { type = "HERB", id = 1455 },
    ["Crystallized Luredrop"] = { type = "HERB", id = 1455 },
    ["Altered Luredrop"] = { type = "HERB", id = 1455 },
    ["Camouflaged Luredrop"] = { type = "HERB", id = 1455 },
    ["Mageroyal"] = { type = "HERB", id = 404 },
    ["Mana Lily"] = { type = "HERB", id = 1483 },
    ["Lush Mana Lily"] = { type = "HERB", id = 1483 },
    ["Lightfused Mana Lily"] = { type = "HERB", id = 1483 },
    ["Primal Mana Lily"] = { type = "HERB", id = 1483 },
    ["Transplanted Mana Lily"] = { type = "HERB", id = 1483 },
    ["Transplanted Lush Mana Lily"] = { type = "HERB", id = 1483 },
    ["Voidbound Mana Lily"] = { type = "HERB", id = 1483 },
    ["Wild Mana Lily"] = { type = "HERB", id = 1483 },
    ["Mana Thistle"] = { type = "HERB", id = 437 },
    ["Marrowroot"] = { type = "HERB", id = 495 },
    ["Mountain Silversage"] = { type = "HERB", id = 427 },
    ["Mycobloom"] = { type = "HERB", id = 1439 },
    ["Lush Mycobloom"] = { type = "HERB", id = 1439 },
    ["Irradiated Mycobloom"] = { type = "HERB", id = 1439 },
    ["Sporefused Mycobloom"] = { type = "HERB", id = 1439 },
    ["Sporelusive Mycobloom"] = { type = "HERB", id = 1439 },
    ["Crystallized Mycobloom"] = { type = "HERB", id = 1439 },
    ["Altered Mycobloom"] = { type = "HERB", id = 1439 },
    ["Camouflaged Mycobloom"] = { type = "HERB", id = 1439 },
    ["Nagrand Arrowbloom"] = { type = "HERB", id = 470 },
    ["Netherbloom"] = { type = "HERB", id = 438 },
    ["Netherdust Bush"] = { type = "HERB", id = 442 },
    ["Nightmare Vine"] = { type = "HERB", id = 439 },
    ["Nightshade"] = { type = "HERB", id = 494 },
    ["Lush Nightshade"] = { type = "HERB", id = 494 },
    ["Elusive Nightshade"] = { type = "HERB", id = 494 },
    ["Lush Elusive Nightshade"] = { type = "HERB", id = 494 },
    ["Orbinid"] = { type = "HERB", id = 1463 },
    ["Lush Orbinid"] = { type = "HERB", id = 1463 },
    ["Irradiated Orbinid"] = { type = "HERB", id = 1463 },
    ["Sporefused Orbinid"] = { type = "HERB", id = 1463 },
    ["Sporelusive Orbinid"] = { type = "HERB", id = 1463 },
    ["Crystallized Orbinid"] = { type = "HERB", id = 1463 },
    ["Altered Orbinid"] = { type = "HERB", id = 1463 },
    ["Camouflaged Orbinid"] = { type = "HERB", id = 1463 },
    ["Peacebloom"] = { type = "HERB", id = 401 },
    ["Phantom Bloom"] = { type = "HERB", id = 1479 },
    ["Lush Phantom Bloom"] = { type = "HERB", id = 1479 },
    ["Plaguebloom"] = { type = "HERB", id = 428 },
    ["Purple Lotus"] = { type = "HERB", id = 418 },
    ["Ragveil"] = { type = "HERB", id = 440 },
    ["Rain Poppy"] = { type = "HERB", id = 467 },
    ["Rising Glory"] = { type = "HERB", id = 497 },
    ["Riverbud"] = { type = "HERB", id = 487 },
    ["Sanguithorn"] = { type = "HERB", id = 1484 },
    ["Lush Sanguithorn"] = { type = "HERB", id = 1484 },
    ["Lightfused Sanguithorn"] = { type = "HERB", id = 1484 },
    ["Primal Sanguithorn"] = { type = "HERB", id = 1484 },
    ["Transplanted Sanguithorn"] = { type = "HERB", id = 1484 },
    ["Transplanted Lush Sanguithorn"] = { type = "HERB", id = 1484 },
    ["Voidbound Sanguithorn"] = { type = "HERB", id = 1484 },
    ["Wild Sanguithorn"] = { type = "HERB", id = 1484 },
    ["Saxifrage"] = { type = "HERB", id = 1421 },
    ["Lush Saxifrage"] = { type = "HERB", id = 1421 },
    ["Frigid Saxifrage"] = { type = "HERB", id = 1421 },
    ["Decayed Saxifrage"] = { type = "HERB", id = 1421 },
    ["Windswept Saxifrage"] = { type = "HERB", id = 1421 },
    ["Infurious Saxifrage"] = { type = "HERB", id = 1421 },
    ["Titan-Touched Saxifrage"] = { type = "HERB", id = 1421 },
    ["Lambent Saxifrage"] = { type = "HERB", id = 1421 },
    ["Sea Stalks"] = { type = "HERB", id = 488 },
    ["Sha-Touched Herb"] = { type = "HERB", id = 468 },
    ["Silkweed"] = { type = "HERB", id = 465 },
    ["Silverleaf"] = { type = "HERB", id = 402 },
    ["Siren's Sting"] = { type = "HERB", id = 489 },
    ["Snow Lily"] = { type = "HERB", id = 464 },
    ["Sorrowmoss"] = { type = "HERB", id = 455 },
    ["Star Moss"] = { type = "HERB", id = 490 },
    ["Starflower"] = { type = "HERB", id = 471 },
    ["Starlight Rose"] = { type = "HERB", id = 481 },
    ["Stormvine"] = { type = "HERB", id = 458 },
    ["Stranglekelp"] = { type = "HERB", id = 407 },
    ["Sungrass"] = { type = "HERB", id = 421 },
    ["Talador Orchid"] = { type = "HERB", id = 469 },
    ["Talandra's Rose"] = { type = "HERB", id = 449 },
    ["Terocone"] = { type = "HERB", id = 434 },
    ["Tiger Lily"] = { type = "HERB", id = 450 },
    ["Tranquility Bloom"] = { type = "HERB", id = 1485 },
    ["Lush Tranquility Bloom"] = { type = "HERB", id = 1485 },
    ["Lightfused Tranquility Bloom"] = { type = "HERB", id = 1485 },
    ["Primal Tranquility Bloom"] = { type = "HERB", id = 1485 },
    ["Transplanted Tranquility Bloom"] = { type = "HERB", id = 1485 },
    ["Transplanted Lush Tranquility Bloom"] = { type = "HERB", id = 1485 },
    ["Voidbound Tranquility Bloom"] = { type = "HERB", id = 1485 },
    ["Wild Tranquility Bloom"] = { type = "HERB", id = 1485 },
    ["Twilight Jasmine"] = { type = "HERB", id = 460 },
    ["Vigil's Torch"] = { type = "HERB", id = 496 },
    ["Whiptail"] = { type = "HERB", id = 461 },
    ["Widowbloom"] = { type = "HERB", id = 498 },
    ["Wild Steelbloom"] = { type = "HERB", id = 409 },
    ["Winter's Kiss"] = { type = "HERB", id = 491 },
    ["Wintersbite"] = { type = "HERB", id = 416 },
    ["Withered Herb"] = { type = "HERB", id = 475 },
    ["Writhebark"] = { type = "HERB", id = 1428 },
    ["Lush Writhebark"] = { type = "HERB", id = 1428 },
    ["Frigid Writhebark"] = { type = "HERB", id = 1428 },
    ["Decayed Writhebark"] = { type = "HERB", id = 1428 },
    ["Windswept Writhebark"] = { type = "HERB", id = 1428 },
    ["Infurious Writhebark"] = { type = "HERB", id = 1428 },
    ["Titan-Touched Writhebark"] = { type = "HERB", id = 1428 },
    ["Lambent Writhebark"] = { type = "HERB", id = 1428 },
    ["Zin'anthid"] = { type = "HERB", id = 492 },
    ["Adamantite Deposit"] = { type = "MINE", id = 222 },
    ["Aqirite"] = { type = "MINE", id = 1226 },
    ["Rich Aqirite"] = { type = "MINE", id = 1226 },
    ["Camouflaged Aqirite"] = { type = "MINE", id = 1226 },
    ["Crystallized Aqirite"] = { type = "MINE", id = 1226 },
    ["Weeping Aqirite"] = { type = "MINE", id = 1226 },
    ["Webbed Aqirite"] = { type = "MINE", id = 1226 },
    ["EZ-Mine Aqirite"] = { type = "MINE", id = 1226 },
    ["Aqirite Seam"] = { type = "MINE", id = 1233 },
    ["Bismuth"] = { type = "MINE", id = 1218 },
    ["Rich Bismuth"] = { type = "MINE", id = 1218 },
    ["Camouflaged Bismuth"] = { type = "MINE", id = 1218 },
    ["Crystallized Bismuth"] = { type = "MINE", id = 1218 },
    ["Weeping Bismuth"] = { type = "MINE", id = 1218 },
    ["Webbed Bismuth"] = { type = "MINE", id = 1218 },
    ["EZ-Mine Bismuth"] = { type = "MINE", id = 1218 },
    ["Bismuth Seam"] = { type = "MINE", id = 1225 },
    ["Blackrock Deposit"] = { type = "MINE", id = 251 },
    ["Brilliant Silver"] = { type = "MINE", id = 1245 },
    ["Rich Brilliant Silver"] = { type = "MINE", id = 1245 },
    ["Lightfused Brilliant Silver"] = { type = "MINE", id = 1245 },
    ["Primal Brilliant Silver"] = { type = "MINE", id = 1245 },
    ["Voidbound Brilliant Silver"] = { type = "MINE", id = 1245 },
    ["Wild Brilliant Silver"] = { type = "MINE", id = 1245 },
    ["Brilliant Silver Seam"] = { type = "MINE", id = 1246 },
    ["Cobalt Deposit"] = { type = "MINE", id = 228 },
    ["Copper Vein"] = { type = "MINE", id = 201 },
    ["Dark Iron Deposit"] = { type = "MINE", id = 217 },
    ["Desolate Deposit"] = { type = "MINE", id = 1243 },
    ["Rich Desolate Deposit"] = { type = "MINE", id = 1243 },
    ["Draconium Seam"] = { type = "MINE", id = 1208 },
    ["Elementium Vein"] = { type = "MINE", id = 236 },
    ["Elethium Deposit"] = { type = "MINE", id = 280 },
    ["Rich Elethium Deposit"] = { type = "MINE", id = 280 },
    ["Elusive Elethium Deposit"] = { type = "MINE", id = 280 },
    ["Elusive Rich Elethium Deposit"] = { type = "MINE", id = 280 },
    ["Empyrium Deposit"] = { type = "MINE", id = 259 },
    ["Empyrium Seam"] = { type = "MINE", id = 261 },
    ["Fel Iron Deposit"] = { type = "MINE", id = 221 },
    ["Felslate Deposit"] = { type = "MINE", id = 256 },
    ["Felslate Seam"] = { type = "MINE", id = 258 },
    ["Ghost Iron Deposit"] = { type = "MINE", id = 241 },
    ["Gold Vein"] = { type = "MINE", id = 205 },
    ["Incendicite Mineral Vein"] = { type = "MINE", id = 219 },
    ["Indurium Mineral Vein"] = { type = "MINE", id = 220 },
    ["Iron Deposit"] = { type = "MINE", id = 203 },
    ["Ironclaw"] = { type = "MINE", id = 1234 },
    ["Rich Ironclaw"] = { type = "MINE", id = 1234 },
    ["Camouflaged Ironclaw"] = { type = "MINE", id = 1234 },
    ["Crystallized Ironclaw"] = { type = "MINE", id = 1234 },
    ["Weeping Ironclaw"] = { type = "MINE", id = 1234 },
    ["Webbed Ironclaw"] = { type = "MINE", id = 1234 },
    ["EZ-Mine Ironclaw"] = { type = "MINE", id = 1234 },
    ["Ironclaw Seam"] = { type = "MINE", id = 1241 },
    ["Khorium Vein"] = { type = "MINE", id = 224 },
    ["Kyparite Deposit"] = { type = "MINE", id = 245 },
    ["Laestrite Deposit"] = { type = "MINE", id = 273 },
    ["Large Obsidian Chunk"] = { type = "MINE", id = 225 },
    ["Lesser Bloodstone Deposit"] = { type = "MINE", id = 218 },
    ["Leystone Deposit"] = { type = "MINE", id = 253 },
    ["Leystone Seam"] = { type = "MINE", id = 255 },
    ["Mithril Deposit"] = { type = "MINE", id = 206 },
    ["Monelite Deposit"] = { type = "MINE", id = 262 },
    ["Monelite Seam"] = { type = "MINE", id = 264 },
    ["Nethercite Deposit"] = { type = "MINE", id = 227 },
    ["Obsidium Deposit"] = { type = "MINE", id = 233 },
    ["Ooze Covered Gold Vein"] = { type = "MINE", id = 210 },
    ["Ooze Covered Mithril Deposit"] = { type = "MINE", id = 207 },
    ["Ooze Covered Rich Thorium Vein"] = { type = "MINE", id = 212 },
    ["Ooze Covered Silver Vein"] = { type = "MINE", id = 209 },
    ["Ooze Covered Thorium Vein"] = { type = "MINE", id = 213 },
    ["Ooze Covered Truesilver Deposit"] = { type = "MINE", id = 211 },
    ["Osmenite Deposit"] = { type = "MINE", id = 270 },
    ["Osmenite Seam"] = { type = "MINE", id = 272 },
    ["Oxxein Deposit"] = { type = "MINE", id = 277 },
    ["Phaedrum Deposit"] = { type = "MINE", id = 275 },
    ["Platinum Deposit"] = { type = "MINE", id = 265 },
    ["Progenium Deposit"] = { type = "MINE", id = 287 },
    ["Rich Progenium Deposit"] = { type = "MINE", id = 287 },
    ["Elusive Progenium Deposit"] = { type = "MINE", id = 287 },
    ["Elusive Rich Progenium Deposit"] = { type = "MINE", id = 287 },
    ["Pure Saronite Deposit"] = { type = "MINE", id = 235 },
    ["Pyrite Deposit"] = { type = "MINE", id = 238 },
    ["Refulgent Copper"] = { type = "MINE", id = 1247 },
    ["Rich Refulgent Copper"] = { type = "MINE", id = 1247 },
    ["Lightfused Refulgent Copper"] = { type = "MINE", id = 1247 },
    ["Primal Refulgent Copper"] = { type = "MINE", id = 1247 },
    ["Voidbound Refulgent Copper"] = { type = "MINE", id = 1247 },
    ["Wild Refulgent Copper"] = { type = "MINE", id = 1247 },
    ["Refulgent Copper Seam"] = { type = "MINE", id = 1248 },
    ["Rich Adamantite Deposit"] = { type = "MINE", id = 223 },
    ["Rich Blackrock Deposit"] = { type = "MINE", id = 252 },
    ["Rich Cobalt Deposit"] = { type = "MINE", id = 229 },
    ["Rich Elementium Vein"] = { type = "MINE", id = 237 },
    ["Rich Empyrium Deposit"] = { type = "MINE", id = 260 },
    ["Rich Felslate Deposit"] = { type = "MINE", id = 257 },
    ["Rich Ghost Iron Deposit"] = { type = "MINE", id = 242 },
    ["Rich Kyparite Deposit"] = { type = "MINE", id = 246 },
    ["Rich Laestrite Deposit"] = { type = "MINE", id = 274 },
    ["Rich Leystone Deposit"] = { type = "MINE", id = 254 },
    ["Rich Monelite Deposit"] = { type = "MINE", id = 263 },
    ["Rich Obsidium Deposit"] = { type = "MINE", id = 239 },
    ["Rich Osmenite Deposit"] = { type = "MINE", id = 271 },
    ["Rich Oxxein Deposit"] = { type = "MINE", id = 278 },
    ["Rich Phaedrum Deposit"] = { type = "MINE", id = 276 },
    ["Rich Platinum Deposit"] = { type = "MINE", id = 266 },
    ["Rich Pyrite Deposit"] = { type = "MINE", id = 240 },
    ["Rich Saronite Deposit"] = { type = "MINE", id = 232 },
    ["Rich Sinvyr Deposit"] = { type = "MINE", id = 285 },
    ["Rich Solenium Deposit"] = { type = "MINE", id = 283 },
    ["Rich Storm Silver Deposit"] = { type = "MINE", id = 268 },
    ["Rich Thorium Vein"] = { type = "MINE", id = 215 },
    ["Rich Trillium Vein"] = { type = "MINE", id = 248 },
    ["Rich True Iron Deposit"] = { type = "MINE", id = 250 },
    ["Saronite Deposit"] = { type = "MINE", id = 231 },
    ["Serevite Deposit"] = { type = "MINE", id = 1201 },
    ["Rich Serevite Deposit"] = { type = "MINE", id = 1201 },
    ["Primal Serevite Deposit"] = { type = "MINE", id = 1201 },
    ["Molten Serevite Deposit"] = { type = "MINE", id = 1201 },
    ["Hardened Serevite Deposit"] = { type = "MINE", id = 1201 },
    ["Infurious Serevite Deposit"] = { type = "MINE", id = 1201 },
    ["Titan-Touched Serevite Deposit"] = { type = "MINE", id = 1201 },
    ["Metamorphic Serevite Deposit"] = { type = "MINE", id = 1201 },
    ["Serevite Seam"] = { type = "MINE", id = 1200 },
    ["Silver Vein"] = { type = "MINE", id = 204 },
    ["Sinvyr Deposit"] = { type = "MINE", id = 284 },
    ["Small Obsidian Chunk"] = { type = "MINE", id = 226 },
    ["Small Thorium Vein"] = { type = "MINE", id = 214 },
    ["Solenium Deposit"] = { type = "MINE", id = 282 },
    ["Storm Silver Deposit"] = { type = "MINE", id = 267 },
    ["Storm Silver Seam"] = { type = "MINE", id = 269 },
    ["Tin Vein"] = { type = "MINE", id = 202 },
    ["Titanium Vein"] = { type = "MINE", id = 230 },
    ["Trillium Vein"] = { type = "MINE", id = 247 },
    ["True Iron Deposit"] = { type = "MINE", id = 249 },
    ["Truesilver Deposit"] = { type = "MINE", id = 208 },
    ["Umbral Tin"] = { type = "MINE", id = 1249 },
    ["Rich Umbral Tin"] = { type = "MINE", id = 1249 },
    ["Lightfused Umbral Tin"] = { type = "MINE", id = 1249 },
    ["Primal Umbral Tin"] = { type = "MINE", id = 1249 },
    ["Voidbound Umbral Tin"] = { type = "MINE", id = 1249 },
    ["Wild Umbral Tin"] = { type = "MINE", id = 1249 },
    ["Umbral Tin Seam"] = { type = "MINE", id = 1250 },
    ["Webbed Ore Deposit"] = { type = "MINE", id = 1242 },
    ["Arden Lumber"] = { type = "LUMBER", id = 712 },
    ["Ashwood Lumber"] = { type = "LUMBER", id = 707 },
    ["Bamboo Lumber"] = { type = "LUMBER", id = 708 },
    ["Coldwind Lumber"] = { type = "LUMBER", id = 706 },
    ["Darkpine Lumber"] = { type = "LUMBER", id = 711 },
    ["Dornic Fir Lumber"] = { type = "LUMBER", id = 714 },
    ["Dragonpine Lumber"] = { type = "LUMBER", id = 713 },
    ["Fel-Touched Lumber"] = { type = "LUMBER", id = 710 },
    ["Ironwood Lumber"] = { type = "LUMBER", id = 704 },
    ["Large Timber"] = { type = "LUMBER", id = 703 },
    ["Olemba Lumber"] = { type = "LUMBER", id = 705 },
    ["Shadowmoon Lumber"] = { type = "LUMBER", id = 709 },
    ["Small Timber"] = { type = "LUMBER", id = 701 },
    ["Thalassian Lumber"] = { type = "LUMBER", id = 715 },
    ["Timber"] = { type = "LUMBER", id = 702 },
    ["Abyssal Gulper School"] = { type = "FISHING", id = 169 },
    ["Aileron Seamoth School"] = { type = "FISHING", id = 1113 },
    ["Albino Cavefish School"] = { type = "FISHING", id = 149 },
    ["Anglerseeker Torrent"] = { type = "FISHING", id = 1127 },
    ["Black Barracuda School"] = { type = "FISHING", id = 182 },
    ["Blackbelly Mudfish School"] = { type = "FISHING", id = 151 },
    ["Blackwater Whiptail School"] = { type = "FISHING", id = 171 },
    ["Blind Lake Sturgeon School"] = { type = "FISHING", id = 172 },
    ["Blood in the Water"] = { type = "FISHING", id = 1123 },
    ["Bloodsail Wreckage Pool"] = { type = "FISHING", id = 135 },
    ["Bloody Perch Swarm"] = { type = "FISHING", id = 1121 },
    ["Bloom Swarm"] = { type = "FISHING", id = 1131 },
    ["Blossoming Torrent"] = { type = "FISHING", id = 1132 },
    ["Bluefish School"] = { type = "FISHING", id = 114 },
    ["Borean Man O' War School"] = { type = "FISHING", id = 121 },
    ["Brackish Mixed School"] = { type = "FISHING", id = 115 },
    ["Bubbling Bloom"] = { type = "FISHING", id = 1133 },
    ["Calm Surfacing Ripple"] = { type = "FISHING", id = 1118 },
    ["Careless Cargo"] = { type = "FISHING", id = 1142 },
    ["Cerulean Spinefish School"] = { type = "FISHING", id = 1114 },
    ["Cursed Queenfish School"] = { type = "FISHING", id = 183 },
    ["Deep Sea Monsterbelly School"] = { type = "FISHING", id = 122 },
    ["Deepsea Sagefish School"] = { type = "FISHING", id = 157 },
    ["Dragonfin Angelfish School"] = { type = "FISHING", id = 123 },
    ["Elysian Thade School"] = { type = "FISHING", id = 1105 },
    ["Emperor Salmon School"] = { type = "FISHING", id = 158 },
    ["Fangtooth Herring School"] = { type = "FISHING", id = 124 },
    ["Fat Sleeper School"] = { type = "FISHING", id = 173 },
    ["Fathom Eel Swarm"] = { type = "FISHING", id = 152 },
    ["Felmouth Frenzy School"] = { type = "FISHING", id = 181 },
    ["Feltail School"] = { type = "FISHING", id = 115 },
    ["Festering Rotpool"] = { type = "FISHING", id = 1124 },
    ["Fever of Stormrays"] = { type = "FISHING", id = 185 },
    ["Fire Ammonite School"] = { type = "FISHING", id = 174 },
    ["Firefin Snapper School"] = { type = "FISHING", id = 105 },
    ["Floating Debris"] = { type = "FISHING", id = 103 },
    ["Floating Deep Treasure"] = { type = "FISHING", id = 1130 },
    ["Floating Shipwreck Debris"] = { type = "FISHING", id = 165 },
    ["Floating Wreckage"] = { type = "FISHING", id = 101 },
    ["Floating Wreckage Pool"] = { type = "FISHING", id = 125 },
    ["Frenzied Fangtooth School"] = { type = "FISHING", id = 188 },
    ["Giant Mantis Shrimp Swarm"] = { type = "FISHING", id = 159 },
    ["Glacial Salmon School"] = { type = "FISHING", id = 126 },
    ["Glassfin Minnow School"] = { type = "FISHING", id = 127 },
    ["Glimmerpool"] = { type = "FISHING", id = 1120 },
    ["Golden Carp School"] = { type = "FISHING", id = 160 },
    ["Great Sea Catfish School"] = { type = "FISHING", id = 189 },
    ["Greater Sagefish School"] = { type = "FISHING", id = 106 },
    ["Highland Guppy School"] = { type = "FISHING", id = 153 },
    ["Highland Mixed School"] = { type = "FISHING", id = 112 },
    ["Highmountain Salmon School"] = { type = "FISHING", id = 186 },
    ["Hunter Surge"] = { type = "FISHING", id = 1134 },
    ["Imperial Manta Ray School"] = { type = "FISHING", id = 128 },
    ["Infused Ichor Spill"] = { type = "FISHING", id = 1125 },
    ["Ionized Minnows"] = { type = "FISHING", id = 199 },
    ["Iridescent Amberjack School"] = { type = "FISHING", id = 1102 },
    ["Islefin Dorado Pool"] = { type = "FISHING", id = 1109 },
    ["Jade Lungfish School"] = { type = "FISHING", id = 161 },
    ["Jawless Skulker School"] = { type = "FISHING", id = 175 },
    ["Jewel Danio School"] = { type = "FISHING", id = 166 },
    ["Krasarang Paddlefish School"] = { type = "FISHING", id = 162 },
    ["Lane Snapper School"] = { type = "FISHING", id = 190 },
    ["Lashing Waves"] = { type = "FISHING", id = 1135 },
    ["Lost Sole School"] = { type = "FISHING", id = 1106 },
    ["Lost Treasures"] = { type = "FISHING", id = 1143 },
    ["Magma Thresher Pool"] = { type = "FISHING", id = 1116 },
    ["Mauve Stinger School"] = { type = "FISHING", id = 197 },
    ["Mixed Ocean School"] = { type = "FISHING", id = 136 },
    ["Moonglow Cuttlefish School"] = { type = "FISHING", id = 129 },
    ["Mossgill Perch School"] = { type = "FISHING", id = 187 },
    ["Mountain Trout School"] = { type = "FISHING", id = 154 },
    ["Mudfish School"] = { type = "FISHING", id = 116 },
    ["Musselback Sculpin School"] = { type = "FISHING", id = 130 },
    ["Nettlefish School"] = { type = "FISHING", id = 131 },
    ["Obscured School"] = { type = "FISHING", id = 1136 },
    ["Oily Abyssal Gulper School"] = { type = "FISHING", id = 170 },
    ["Oily Blackmouth School"] = { type = "FISHING", id = 107 },
    ["Oily Sea Scorpion School"] = { type = "FISHING", id = 177 },
    ["Pocked Bonefish School"] = { type = "FISHING", id = 1103 },
    ["Pool of Fire"] = { type = "FISHING", id = 155 },
    ["Precursor Placoderm School"] = { type = "FISHING", id = 1108 },
    ["Prismatic Leaper School"] = { type = "FISHING", id = 1117 },
    ["Pure Water"] = { type = "FISHING", id = 113 },
    ["Rasboralus School"] = { type = "FISHING", id = 191 },
    ["Redbelly Mandarin School"] = { type = "FISHING", id = 163 },
    ["Redtail Loach School"] = { type = "FISHING", id = 192 },
    ["Reef Octopus Swarm"] = { type = "FISHING", id = 164 },
    ["Rimefin Tuna Pool"] = { type = "FISHING", id = 1115 },
    ["River Bass Pool"] = { type = "FISHING", id = 1119 },
    ["Royal Ripple"] = { type = "FISHING", id = 1128 },
    ["Runescale Koi School"] = { type = "FISHING", id = 184 },
    ["Sagefish School"] = { type = "FISHING", id = 108 },
    ["Salmon Pool"] = { type = "FISHING", id = 1137 },
    ["Sand Shifter School"] = { type = "FISHING", id = 193 },
    ["Savage Piranha Pool"] = { type = "FISHING", id = 178 },
    ["School of Darter"] = { type = "FISHING", id = 117 },
    ["School of Deviate Fish"] = { type = "FISHING", id = 109 },
    ["School of Tastyfish"] = { type = "FISHING", id = 120 },
    ["Schooner Wreckage"] = { type = "FISHING", id = 133 },
    ["Sea Scorpion School"] = { type = "FISHING", id = 176 },
    ["Sentry Fish School"] = { type = "FISHING", id = 1101 },
    ["Shimmering Treasure Pool"] = { type = "FISHING", id = 1110 },
    ["Shipwreck Debris"] = { type = "FISHING", id = 156 },
    ["Shore Treasure"] = { type = "FISHING", id = 1129 },
    ["Silvergill Pike School"] = { type = "FISHING", id = 1104 },
    ["Slimy Mackerel School"] = { type = "FISHING", id = 194 },
    ["Song Swarm"] = { type = "FISHING", id = 1138 },
    ["Spinefin Piranha School"] = { type = "FISHING", id = 1107 },
    ["Spinefish School"] = { type = "FISHING", id = 167 },
    ["Sporefish School"] = { type = "FISHING", id = 118 },
    ["Stargazer Swarm"] = { type = "FISHING", id = 1126 },
    ["Steam Pump Flotsam"] = { type = "FISHING", id = 119 },
    ["Stonescale Eel Swarm"] = { type = "FISHING", id = 110 },
    ["Strange Pool"] = { type = "FISHING", id = 132 },
    ["Sunbath School"] = { type = "FISHING", id = 1139 },
    ["Sunwell Swarm"] = { type = "FISHING", id = 1140 },
    ["Surface Ripple"] = { type = "FISHING", id = 1141 },
    ["Swarm of Slum Sharks"] = { type = "FISHING", id = 1122 },
    ["Temporal Dragonhead Pool"] = { type = "FISHING", id = 1111 },
    ["Thousandbite Pirahna Swarm"] = { type = "FISHING", id = 1112 },
    ["Tiger Gourami School"] = { type = "FISHING", id = 168 },
    ["Tiragarde Perch School"] = { type = "FISHING", id = 195 },
    ["U'taka School"] = { type = "FISHING", id = 196 },
    ["Viper Fish School"] = { type = "FISHING", id = 198 },
    ["Viscous Void"] = { type = "FISHING", id = 1144 },
    ["Waterlogged Wreckage Pool"] = { type = "FISHING", id = 134 },
    ["Adamantite Bound Chest"] = { type = "TREASURE", id = 523 },
    ["Ancient Mana Chunk"] = { type = "TREASURE", id = 553 },
    ["Ancient Mana Crystal"] = { type = "TREASURE", id = 554 },
    ["Ancient Mana Shard"] = { type = "TREASURE", id = 552 },
    ["Battered Chest"] = { type = "TREASURE", id = 502 },
    ["Battered Footlocker"] = { type = "TREASURE", id = 515 },
    ["Bloodpetal Sprout"] = { type = "TREASURE", id = 512 },
    ["Bound Adamantite Chest"] = { type = "TREASURE", id = 530 },
    ["Bound Fel Iron Chest"] = { type = "TREASURE", id = 529 },
    ["Brightly Colored Egg"] = { type = "TREASURE", id = 533 },
    ["Buccaneer's Strongbox"] = { type = "TREASURE", id = 508 },
    ["Burial Chest"] = { type = "TREASURE", id = 520 },
    ["Dark Iron Treasure Chest"] = { type = "TREASURE", id = 539 },
    ["Dark Soil"] = { type = "TREASURE", id = 545 },
    ["Dart's Nest"] = { type = "TREASURE", id = 542 },
    ["Dented Footlocker"] = { type = "TREASURE", id = 517 },
    ["Disturbed Earth"] = { type = "TREASURE", id = 566 },
    ["Everfrost Chip"] = { type = "TREASURE", id = 532 },
    ["Fel Iron Chest"] = { type = "TREASURE", id = 521 },
    ["Felsteel Chest"] = { type = "TREASURE", id = 524 },
    ["Giant Clam"] = { type = "TREASURE", id = 501 },
    ["Gleaming Draenic Chest"] = { type = "TREASURE", id = 551 },
    ["Glimmering Chest"] = { type = "TREASURE", id = 561 },
    ["Glowcap"] = { type = "TREASURE", id = 525 },
    ["Glowing Tome"] = { type = "TREASURE", id = 557 },
    ["Ground Wart"] = { type = "TREASURE", id = 565 },
    ["Heavy Fel Iron Chest"] = { type = "TREASURE", id = 522 },
    ["Highmaul Reliquary"] = { type = "TREASURE", id = 548 },
    ["Jelly Deposit"] = { type = "TREASURE", id = 563 },
    ["Large Battered Chest"] = { type = "TREASURE", id = 507 },
    ["Large Darkwood Chest"] = { type = "TREASURE", id = 510 },
    ["Large Iron Bound Chest"] = { type = "TREASURE", id = 505 },
    ["Large Jelly Deposit"] = { type = "TREASURE", id = 564 },
    ["Large Mithril Bound Chest"] = { type = "TREASURE", id = 509 },
    ["Large Solid Chest"] = { type = "TREASURE", id = 506 },
    ["Leypetal Blossom"] = { type = "TREASURE", id = 555 },
    ["Leypetal Powder"] = { type = "TREASURE", id = 556 },
    ["Mana-Infused Gem"] = { type = "TREASURE", id = 558 },
    ["Maplewood Treasure Chest"] = { type = "TREASURE", id = 540 },
    ["Mechanized Chest"] = { type = "TREASURE", id = 560 },
    ["Mossy Footlocker"] = { type = "TREASURE", id = 518 },
    ["Mysterious Camel Figurine"] = { type = "TREASURE", id = 538 },
    ["Netherwing Egg"] = { type = "TREASURE", id = 531 },
    ["Onyx Egg"] = { type = "TREASURE", id = 546 },
    ["Practice Lockbox"] = { type = "TREASURE", id = 514 },
    ["Primitive Chest"] = { type = "TREASURE", id = 527 },
    ["Prismatic Crystal"] = { type = "TREASURE", id = 562 },
    ["Radiating Apexis Shard"] = { type = "TREASURE", id = 550 },
    ["Ravasaur Matriarch's Nest"] = { type = "TREASURE", id = 544 },
    ["Razormaw Matriarch's Nest"] = { type = "TREASURE", id = 543 },
    ["Runestone Treasure Chest"] = { type = "TREASURE", id = 536 },
    ["Scarlet Footlocker"] = { type = "TREASURE", id = 519 },
    ["Silken Treasure Chest"] = { type = "TREASURE", id = 534 },
    ["Silverbound Treasure Chest"] = { type = "TREASURE", id = 537 },
    ["Solid Chest"] = { type = "TREASURE", id = 504 },
    ["Solid Fel Iron Chest"] = { type = "TREASURE", id = 528 },
    ["Sturdy Treasure Chest"] = { type = "TREASURE", id = 535 },
    ["Suspiciously Glowing Chest"] = { type = "TREASURE", id = 549 },
    ["Takk's Nest"] = { type = "TREASURE", id = 541 },
    ["Tattered Chest"] = { type = "TREASURE", id = 503 },
    ["Trove of the Thunder King"] = { type = "TREASURE", id = 547 },
    ["Twice-Fortified Arcwine"] = { type = "TREASURE", id = 559 },
    ["Waterlogged Footlocker"] = { type = "TREASURE", id = 516 },
    ["Wicker Chest"] = { type = "TREASURE", id = 526 },
}

-- REGENERATING: parse GatherMate2/Constants.lua -- its node_ids table carries the
-- species numbers the GatherMate seed data is keyed on, plus the variant names --
-- and re-emit this file. Only numbers and names are taken, and both of those are
-- Blizzard's. Do this when an expansion adds herbs; nothing else here rots.
